# PIPELINE DEFINITION
# Name: mlops-assignment-4-pipeline
# Description: A pipeline that preprocesses data and trains a model.
# Inputs:
#    input_data_path: str [Default: '/tmp/data/city_A.csv']
#    n_estimators: int [Default: 100.0]
#    test_size: float [Default: 0.2]
components:
  comp-data-preprocessing:
    executorLabel: exec-data-preprocessing
    inputDefinitions:
      artifacts:
        input_data_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
      parameters:
        test_size:
          defaultValue: 0.2
          isOptional: true
          parameterType: NUMBER_DOUBLE
    outputDefinitions:
      artifacts:
        x_test_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
        x_train_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
        y_test_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
        y_train_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
  comp-importer:
    executorLabel: exec-importer
    inputDefinitions:
      parameters:
        uri:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        artifact:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
  comp-model-training:
    executorLabel: exec-model-training
    inputDefinitions:
      artifacts:
        x_train_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
        y_train_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
      parameters:
        n_estimators:
          defaultValue: 100.0
          isOptional: true
          parameterType: NUMBER_INTEGER
    outputDefinitions:
      artifacts:
        model_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-data-preprocessing:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - data_preprocessing
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'pandas' 'scikit-learn'\
          \ 'dvc'  &&  python3 -m pip install --quiet --no-warn-script-location 'kfp==2.14.6'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef data_preprocessing(\n    input_data_path: InputPath('CSV'),\n\
          \    x_train_path: OutputPath('CSV'),\n    x_test_path: OutputPath('CSV'),\n\
          \    y_train_path: OutputPath('CSV'),\n    y_test_path: OutputPath('CSV'),\n\
          \    test_size: float = 0.2\n):\n    \"\"\"\n    A component to preprocess\
          \ the data.\n    \"\"\"\n    import pandas as pd\n    from sklearn.model_selection\
          \ import train_test_split\n    from sklearn.preprocessing import StandardScaler\n\
          \n    # Read data\n    df = pd.read_csv(input_data_path)\n\n    # Handle\
          \ missing values if any\n    df = df.dropna()\n\n    # Separate features\
          \ and target\n    X = df.drop('MEDV', axis=1)  # Assuming 'MEDV' is the\
          \ target column\n    y = df['MEDV']\n\n    # Split the data\n    X_train,\
          \ X_test, y_train, y_test = train_test_split(X, y, test_size=test_size,\
          \ random_state=42)\n\n    # Scale the features\n    scaler = StandardScaler()\n\
          \    X_train_scaled = scaler.fit_transform(X_train)\n    X_test_scaled =\
          \ scaler.transform(X_test)\n\n    # Convert back to DataFrame for easier\
          \ saving\n    X_train_df = pd.DataFrame(X_train_scaled, columns=X.columns)\n\
          \    X_test_df = pd.DataFrame(X_test_scaled, columns=X.columns)\n\n    #\
          \ Save the processed data to the output paths provided by KFP\n    X_train_df.to_csv(x_train_path,\
          \ index=False)\n    X_test_df.to_csv(x_test_path, index=False)\n    y_train.to_csv(y_train_path,\
          \ index=False)\n    y_test.to_csv(y_test_path, index=False)\n\n"
        image: python:3.9
    exec-importer:
      importer:
        artifactUri:
          runtimeParameter: uri
        typeSchema:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
    exec-model-training:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - model_training
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'scikit-learn'\
          \ 'pandas' 'joblib'  &&  python3 -m pip install --quiet --no-warn-script-location\
          \ 'kfp==2.14.6' '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"\
          3.9\"' && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef model_training(\n    x_train_path: InputPath('CSV'),\n    y_train_path:\
          \ InputPath('CSV'),\n    model_path: OutputPath('Joblib'),\n    n_estimators:\
          \ int = 100\n):\n    \"\"\"\n    A component to train a Random Forest model.\n\
          \    \"\"\"\n    import pandas as pd\n    from sklearn.ensemble import RandomForestRegressor\n\
          \    import joblib\n\n    # Load the preprocessed data\n    X_train = pd.read_csv(x_train_path)\n\
          \    y_train = pd.read_csv(y_train_path).squeeze('columns')  # Convert DataFrame\
          \ to Series\n\n    # Train the model\n    model = RandomForestRegressor(n_estimators=n_estimators,\
          \ random_state=42)\n    model.fit(X_train, y_train)\n\n    # Save the trained\
          \ model\n    joblib.dump(model, model_path)\n\n"
        image: python:3.9
pipelineInfo:
  description: A pipeline that preprocesses data and trains a model.
  name: mlops-assignment-4-pipeline
root:
  dag:
    tasks:
      data-preprocessing:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-data-preprocessing
        dependentTasks:
        - importer
        inputs:
          artifacts:
            input_data_path:
              taskOutputArtifact:
                outputArtifactKey: artifact
                producerTask: importer
          parameters:
            test_size:
              componentInputParameter: test_size
        taskInfo:
          name: data-preprocessing
      importer:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-importer
        inputs:
          parameters:
            uri:
              componentInputParameter: input_data_path
        taskInfo:
          name: importer
      model-training:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-model-training
        dependentTasks:
        - data-preprocessing
        inputs:
          artifacts:
            x_train_path:
              taskOutputArtifact:
                outputArtifactKey: x_train_path
                producerTask: data-preprocessing
            y_train_path:
              taskOutputArtifact:
                outputArtifactKey: y_train_path
                producerTask: data-preprocessing
          parameters:
            n_estimators:
              componentInputParameter: n_estimators
        taskInfo:
          name: model-training
  inputDefinitions:
    parameters:
      input_data_path:
        defaultValue: /tmp/data/city_A.csv
        isOptional: true
        parameterType: STRING
      n_estimators:
        defaultValue: 100.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      test_size:
        defaultValue: 0.2
        isOptional: true
        parameterType: NUMBER_DOUBLE
schemaVersion: 2.1.0
sdkVersion: kfp-2.14.6
